export const STRINGS = {
  errors: {
    invalidProject: "올바른 프로젝트 파일이 아닙니다.",
    unsupportedVersion: (version) => `지원하지 않는 프로젝트 버전입니다: ${version ?? "알 수 없음"}`,
    invalidWidth: "디자인 너비가 올바르지 않습니다.",
    invalidHeight: "디자인 높이가 올바르지 않습니다.",
    missingBackgroundAsset: "배경 이미지 에셋을 찾을 수 없습니다.",
    missingAsset: "이미지 에셋을 찾을 수 없습니다.",
    invalidProjectAsset: "프로젝트 파일 안의 이미지가 손상되었습니다.",
    projectMissingAsset: "프로젝트 파일에 필요한 이미지가 빠져 있습니다.",
    imageDecode: "이미지를 불러오지 못했습니다.",
    fileRead: "파일을 읽지 못했습니다.",
    exportNeedsBackground: "시트 크기가 올바르지 않아 내보낼 수 없어요.",
    exportFailed: "PNG 내보내기에 실패했습니다.",
    coasterList: "코스터 목록(coasters.json)을 불러오지 못했어요. Go Live로 열었는지, 파일 내용이 올바른지 확인해 주세요.",
    patternList: "패턴 목록(patterns.json)을 불러오지 못했어요. Go Live로 열었는지, 파일 내용이 올바른지 확인해 주세요.",
  },
  unsaved: "저장하지 않은 변경사항이 있습니다.",
  patternNone: "패턴 없음",
  coasterNone: "코스터 없음",
  coasterPlate: "코드로 그린 받침",
  coasterGroupFile: "PNG 코스터 (폴더)",
  edgeStyles: {
    smooth: "매끈",
    wave: "물결",
    lace: "스캘럽 (레이스)",
    zigzag: "톱니",
    petal: "꽃잎",
    ruffle: "러플",
    spike: "뾰족 별",
    notch: "티켓 구멍",
  },
  none: "없음",
  frameShapes: { arch: "아치 (돔)", rect: "직사각형", rounded: "둥근 직사각형", oval: "타원", pill: "알약" },
  frameFills: { solid: "단색", linear: "그라데이션" },
  borderStyles: { line: "기본 선", multi: "여러 겹 선", offset: "겹친 프레임", picture: "액자 틀", pictureMat: "액자 틀 + 매트", scallop: "스캘럽 (물결 테두리)", dotted: "도트", stitch: "스티치 (바느질)" },
  topTypes: { none: "없음", sparkleCluster: "반짝이 무리", bow: "큰 리본", valance: "물결 커튼", moon: "달", bigSparkle: "큰 반짝이", medallion: "원형 메달" },
  frameAutoHint: "배경색에 맞춰 선·바탕·장식 색이 자동으로 정해져요. 끄면 직접 고른 색으로 돌아가요.",
  decorFrameHint: "장식은 프레임 모양을 따라 붙어요. 모서리 장식은 한 가지를 고르면 네 모서리에 뒤집혀서 들어가요.",
  stickerEmpty: "아직 붙인 스티커가 없어요. 위에서 고르고 '시트에 붙이기'를 눌러요.",
  stickerHint: "미리보기에서 끌어서 옮기고 Ctrl + 휠로 크기를 바꿔요. 스티커를 클릭하면 선택돼요. 폴더 스티커는 assets/stickers 에 넣고 stickers.json 에 이름을 적으면 목록에 나타나요 (없어도 괜찮아요).",
  trayShapes: { rounded: "둥근 네모", ellipse: "타원" },
  brandHint: "시트 전체에 속한 로고예요. 미리보기에서 끌어서 옮기고 Ctrl + 휠로 크기를 바꿔요. 기본 글꼴은 학교안심 퍼즐이고, 다른 글꼴로 바꿀 수 있어요.",
  textEffects: { normal: "기본", neon: "네온 (빛 번짐)", comic: "코믹 (외곽선 + 그림자)" },
  cardHint: "카드 안 배치는 고정이에요. 글자와 색, 그림만 바꿔요. 재료는 신청자가 '빠지면 안 된다'고 한 요소를 적어요.",
  cardGarnishTooLong: (rows) => `가니쉬 ${rows.join(", ")}번이 너무 길어서 두 줄로도 안 들어가요.`,
  cardPastSheet: "카드가 길어져서 시트 아래로 넘쳤어요. 카드를 위로 옮기거나 폭·글자 크기를 조절해 주세요.",
  cardNoImage: "아직 올린 칵테일 그림이 없어요",
  cardTooMany: "재료가 칸을 넘쳤어요. 줄이거나 글자 크기를 조절해 주세요.",
  cardTooLong: (rows) => `${rows.join(", ")}번 재료가 길어서 용량과 겹쳐요. "긴 재료는 두 줄로"를 켜거나 그림 칸 너비를 줄여보세요.`,
  confettiHint: "뒤 컨페티는 프레임 뒤에, 앞 컨페티는 코스터 위·캐릭터 아래에 깔려요. 캐릭터의 불투명한 부분은 절대 덮지 않아요. 배치는 '다시 뽑기'를 누를 때만 바뀌어요.",
  paletteOrderNote: (hex) => `지금 ORDER: ${hex} — 누르면 첫 번째 색에 한 번 복사돼요. 이후 ORDER를 바꿔도 팔레트는 그대로예요.`,
  paletteOrderEmpty: "ORDER HEX가 비어 있어요. 칵테일 카드나 영수증에서 먼저 적어주세요.",
  receiptContentRule: "신청자가 신청서에 직접 적은 내용만 넣어요. 추가금 옵션은 넣지 않아요.",
  receiptPastBoard: "영수증이 판보다 길어졌어요. 항목을 줄이거나 글자 크기, 판 비율을 조절해 주세요.",
  receiptRowsCollide: (rows) => `${rows.join(", ")} 항목이 길어서 오른쪽 값과 겹쳐요.`,
  anniversaryInvalid: "실제 있는 날짜를 YYYYMMDD 8자리로 적어주세요. (예: 20261001)",
  codeUsesAnniversary: (random) => `지금은 기념일이 표시돼요. 기념일을 지우면 랜덤 번호 ${random}가 나와요.`,
  codeUsesRandom: (random) => `지금 번호: ${random} (다시 뽑기를 누를 때만 바뀌어요)`,
  decorLimit: (n) => `최대 ${n}글자까지 쓸 수 있어요.`,
  decorHint: "글자는 받침 모양을 따라 휘어져요. 각도 -90 = 위, 90 = 아래 (아래쪽도 글자가 바로 보여요).",
  syncHint: "켜면 지금 이 받침의 디자인이 다른 받침에도 복사되고, 이후 색·테두리·패턴·장식 글자가 같이 바뀌어요. 위치·크기·모양(납작함)과 패턴 배치는 각자 따로예요.",
  fontMissing: "이 글꼴 파일을 찾을 수 없어서 임시 글꼴로 보여요 (assets/fonts 폴더와 css/fonts.css 확인).",
  coasterMissing: (file) => `코스터 파일을 찾을 수 없어요: ${file}. assets/coasters 폴더와 coasters.json을 확인해 주세요.`,
  characterNone: "아직 올린 캐릭터가 없어요",
  characterUpload: "올리기",
  characterReplace: "바꾸기",
  patternGroupBuiltin: "기본 패턴",
  patternGroupFile: "내 패턴 (폴더)",
  patternNotListed: (file) => `(목록에 없음) ${file}`,
  patternMissing: (file) => `패턴 파일을 찾을 수 없어요: ${file}. assets/backgrounds 폴더와 patterns.json을 확인해 주세요.`,
  patternSizeNotice: (w, h, sw, sh) =>
    `패턴 크기(${w}×${h})가 시트(${sw}×${sh})와 달라서, 시트 크기에 맞춰 늘려서 그려요.`,
  invalidHex: "HEX 코드는 #FFFFFF 처럼 6자리로 입력해 주세요.",
};
